# Generated by Django 3.2.13 on 2023-05-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_review_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like_users',
        ),
    ]
